### ISSUE TITLE
Output is null

### ISSUE THREAD

**Issue by Happy-Ferret** [fmovlex/desprite#5]
Given the below png and the following CSS, desprite produces absolutely nothing.

Does this tool only work with specifically prepared PNGs or is there something I'm doing fundamentally wrong?

```css
.walk {
  background: url(walk_north.png) -11px, -49px;
  width: 32px;
  height: 32px;
}
```

![walk_north](https://user-images.githubusercontent.com/1962554/57538835-80aae100-7349-11e9-8bfb-9eb5ed1d1ffd.png)
